name: "terminus"

services:
  web:
    init: true
    build:
      context: .
    environment:
      RACK_ENV: development
      HANAMI_PORT: ${HANAMI_PORT}
      API_URI: ${API_URI}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@database:5432/${PG_DATABASE}
    ports:
      - "${HANAMI_PORT}:${HANAMI_PORT}"
    restart: unless-stopped
    volumes:
      - web-uploads:/app/public/uploads
    depends_on:
      database:
        condition: service_healthy
    labels:
      # --- NEW --- Tells Traefik to manage this container
      - 'traefik.enable=true'
      # --- NEW --- The routing rule. Coolify provides the FQDN variable automatically.
      - 'traefik.http.routers.terminus-web.rule=Host(`${COOLIFY_FQDN}`)'
      # --- NEW --- Tells Traefik to use the secure (HTTPS) entrypoint.
      - 'traefik.http.routers.terminus-web.entrypoints=websecure'
      # --- NEW --- Tells Traefik which port your app uses INSIDE the container.
      - 'traefik.http.services.terminus-web.loadbalancer.server.port=${HANAMI_PORT}'

      # --- Your existing labels ---
      - 'traefik.http.middlewares.mybasicauth.basicauth.users=${BASIC_AUTH_USERS}'
      - 'traefik.http.routers.terminus-web.middlewares=mybasicauth'
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  database:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

volumes:
  database-data:
  web-uploads:
